server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'
  
spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser-v2
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  output:
    ansi:
      enabled: Always       # mostra o console com letras coloridas
  rabbitmq:
    address: amqps://dmzqktbw:qYBoCh_nC6gqUTVxiOTgdIwwXFf4-q-m@shark.rmq.cloudamqp.com/dmzqktbw

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG   # Caso queira ver o log dessas dependencias
    org.hibernate: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
