server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show-sql: true
  output:
    ansi:
      enabled: Always       # mostra o console com letras coloridas

ead:
  api:
    url:
      course: 'http://localhost:8082/ead-course'

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG   # Caso queira ver o log dessas dependencias
    org.hibernate: INFO