server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course-v2
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  output:
    ansi:
      enabled: Always       # mostra o console com letras coloridas
  rabbitmq:
    host: shark.rmq.cloudamqp.com
    port: 5671
    username: dmzqktbw
    password: qYBoCh_nC6gqUTVxiOTgdIwwXFf4-q-m
    virtual-host: dmzqktbw
    ssl:
      enabled: true

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'

logging:
  level:
    com.ead: TRACE
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost